name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - master
    - rel/*
pr:
- '*'
resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   thnetii
jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    presteps:
    - checkout:   self
      submodules: true
    overrideCommon:
      allProjects: |
        [Ss]ample/*/*.csproj
        [Ss]rc/*/*.csproj
        [Tt]est/*/*.csproj
      srcProjects: |
        [Ss]ample/*/*.csproj
        [Ss]rc/*/*.csproj
    disableWindowsRuntime: true
    addRuntimes:
    - id:           win
      condition:    ne(variables['SkipWindowsRuntime'], 'true')
      argValue:     win10-x64
      displayName:  Windows, 64-bit
      pool:
        vmImage:    windows-latest
      restore:
        projects: |
          [Ss]ample/*/*.csproj
          [Ss]rc/*/*.csproj
          [Tt]est/*/*.csproj
          [Ss]ample-win/*/*.csproj
          [Ss]rc-win/*/*.csproj
          [Tt]est-win/*/*.csproj
      build:
        projects: |
          [Ss]ample/*/*.csproj
          [Ss]rc/*/*.csproj
          [Tt]est/*/*.csproj
          [Ss]ample-win/*/*.csproj
          [Ss]rc-win/*/*.csproj
          [Tt]est-win/*/*.csproj
      test:
        project: |
          [Tt]est/*/*.csproj
          [Tt]est-win/*/*.csproj
      pack:
        skip:       true
      publish:
        project: |
          [Ss]rc/*/*.csproj
          [Ss]rc-win/*/*.csproj
          [Ss]ample/*/*.csproj
          [Ss]ample-win/*/*.csproj
    #- id:           win_no_rid
    #  condition:    ne(variables['SkipWindowsRuntime'], 'true')
    #  displayName:  Windows, 64-bit (No RID)
    #  pool:
    #    vmImage:    windows-latest
    #  restore:
    #    projects: |
    #      [Ss]ample/*/*.csproj
    #      [Ss]rc/*/*.csproj
    #      [Tt]est/*/*.csproj
    #      [Ss]ample-win/*/*.csproj
    #      [Ss]rc-win/*/*.csproj
    #      [Tt]est-win/*/*.csproj
    #  build:
    #    projects: |
    #      [Ss]ample/*/*.csproj
    #      [Ss]rc/*/*.csproj
    #      [Tt]est/*/*.csproj
    #      [Ss]ample-win/*/*.csproj
    #      [Ss]rc-win/*/*.csproj
    #      [Tt]est-win/*/*.csproj
    #  test:
    #    project: |
    #      [Tt]est/*/*.csproj
    #      [Tt]est-win/*/*.csproj
    #  pack:
    #    projects: |
    #      [Ss]rc-win/*/*.csproj
    #  publish:
    #    projects: |
    #      [Ss]rc-win/*/*.csproj
